# Generated by Django 5.0.3 on 2024-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
