# Generated by Django 5.0.3 on 2024-06-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_address_customers_customers_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='customers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='app.customers'),
            preserve_default=False,
        ),
    ]
